title: "Engineering Articles"
description: "DevSecOps, Security Engineering, and Scalable Systems"
baseurl: "/engineering-articles"
theme: jekyll-theme-cayman   # tema moderno e limpo do GitHub Pages
markdown: kramdown
collections:
  articles:
    output: true
    permalink: /:path/
defaults:
  - scope:
      path: ""
      type: articles
    values:
      layout: default
