title: "Otávio Tavares | Engineering Articles"
description: "DevSecOps, Security Engineering, and Scalable Systems"
theme: minima

markdown: kramdown

collections:
  articles:
    output: true

defaults:
  - scope:
      path: ""
      type: "articles"
    values:
      layout: "post"
